name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # setiap hari
  workflow_dispatch: # bisa juga dijalankan manual

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: adamkennedy
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg

      - name: Push snake files to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
